echo "********************************************************************"
echo "*                                                                  *"
echo "*   Welcome to OBL Linux!                                          *"
echo "*                                                                  *"
echo "*   - Get information of your PC : lspci                           *"
echo "*   - Start a graphical display  : startx                          *"
echo "*   - Startx with bigger fonts   : startx -- -dpi 192              *"
echo "*   ___  ____  _       _     _                                     *"
echo "*  / _ \| __ )| |     | |   (_)_ __  _   ___  __                   *"
echo "* | | | |  _ \| |     | |   | | '_ \| | | \ \/ /                   *"
echo "* | |_| | |_) | |___  | |___| | | | | |_| |>  <                    *"
echo "*  \___/|____/|_____| |_____|_|_| |_|\__,_/_/\_\                   *"
echo "********************************************************************"
